[project]
name = "django-4-dronov-vladimir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django~=4.1",
    "mysqlclient>=2.2.7",
    "psycopg2-binary>=2.9.10",
]
